# Generated by Django 2.2.13 on 2020-06-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegExpFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('blacklist', 'Blacklist'), ('whitelist', 'Whitelist')], max_length=9, verbose_name='Filter type')),
                ('reg_exp_lists', models.TextField(max_length=500, verbose_name='List of regular expressions')),
            ],
        ),
    ]
