# Generated by Django 2.2.13 on 2020-06-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegExFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('filter_type', models.CharField(choices=[('blacklist', 'Blacklist'), ('whitelist', 'Whitelist')], help_text='Whitelist: Only events matching the regular expressions in the list will be allowed to passed through.<br/>Blacklist: Events matching any regular expression in the list will be blocked.', max_length=9, verbose_name='Filter type')),
                ('regular_expressions', models.TextField(help_text='This should be a comma-seperated list of regular expressions for the events to be filtered.', max_length=500, verbose_name='List of regular expressions')),
            ],
        ),
    ]
