# Generated by Django 2.2.13 on 2020-06-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventtracking_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regexpfilter',
            name='filter_type',
            field=models.CharField(choices=[('blacklist', 'Blacklist'), ('whitelist', 'Whitelist')], help_text='Whitelist: Only events matching the regular expressions in the list will be allowed to passed through.<br/>Blacklist: Events matching any regular expression in the list will be blocked.', max_length=9, verbose_name='Filter type'),
        ),
        migrations.AlterField(
            model_name='regexpfilter',
            name='reg_exp_lists',
            field=models.TextField(help_text='This should be a comma-seperated list of regular expressions for the events to be filtered.', max_length=500, verbose_name='List of regular expressions'),
        ),
    ]
