# Generated by Django 2.2.13 on 2020-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventtracking_django', '0002_auto_20200629_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexpfilter',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Is Enabled'),
        ),
    ]
